---
- name: Criar diretório do site
  file:
    path: "{{ document_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Configurar Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx

- name: Criar página de exemplo
  template:
    src: index.html.j2
    dest: "{{ document_root }}/index.html"
    owner: www-data
    group: www-data
    mode: '0644'
