---
- name: Configurar servidores web
  hosts: my_vm
  become: yes
  vars:
    nginx_port: 8080
    document_root: /var/www/html/
  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes
      tags: 
        - always

    - name: Instalar Nginx
      apt:
        name: nginx
        state: present

    - name: Aplicar configuração Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

