---
- name: Configure Nginx
  hosts: all
  become: true
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: "{{ package_name }}"
        state: present

    - name: Stop and disable Apache if running
      ansible.builtin.service:
        name: "{{ apache_service }}"
        state: stopped
        enabled: false

    - name: Validate Nginx configuration before starting
      command: nginx -t
      register: nginx_test
      changed_when: nginx_test.rc != 0

    - name: Ensure Nginx is running
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: started
        enabled: true
      when: nginx_test.rc == 0
