- name: Instalar Apache
  apt:
    name: apache2
    state: present
    update_cache: yes
  tags:
    - install

- name: Copiar index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
  tags:
    - install

- name: Ativar e iniciar Apache
  service:
    name: apache2
    state: started
    enabled: yes
  notify: restart apache
  tags:
    - install

- name: Remover Apache
  apt:
    name: apache2
    state: absent
    purge: yes
  tags:
    - remove

- name: Remover arquivos do Apache
  file:
    path: /var/www/html
    state: absent
  tags:
    - remove
    