---
- name: Create a user
  hosts: all
  become: true

  tasks:
    - name: Add a user
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        groups: "{{ user_group }}"
