---
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present

    - name: Iniciar serviço Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copiar arquivo de configuração personalizado
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Reiniciar Nginx

    - name: Check if Nginx is running using service
      shell: service nginx status
      register: nginx_status
      ignore_errors: yes

    - name: Debug Nginx status output
      debug:
        msg: "{{ nginx_status.stdout }}"

    - name: Verify Nginx is responding
      uri:
        url: http://localhost
        status_code: 200
      register: nginx_response
      ignore_errors: yes
