---
- name: Configure Apache
  hosts: all
  become: true
  vars:
    apache_package: apache2
    apache_service: apache2

  tasks:
    - name: Install Apache
      ansible.builtin.yum:
        name: "{{ apache_package }}"
        state: present

    - name: Ensure Apache is running
      ansible.builtin.service:
        name: "{{ apache_service }}"
        state: started
        enabled: true
