---
- name: Export Ansible Facts in Pretty JSON
  hosts: all
  gather_facts: yes
  tasks:
    - name: Save Facts in a JSON File
      copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: "./facts_{{ inventory_hostname }}.json"
